---
sudo: false

language: go

go:
  - 1.x

env:
  global:
    - CGO_ENABLED=0
    - VERSION=$TRAVIS_TAG
    - GIT_SHA=${TRAVIS_COMMIT:0:7}
    - LABELS_TRIM=1
    - LABELS_PR=0

cache:
  directories:
    - $GOPATH/bin

install: true

before_script:
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install

script:
  - go test $(go list ./... | grep -v /vendor/)
  - gometalinter.v1 --vendor ./... || true
  - openssl aes-256-cbc -K $encrypted_8ac6028fa38c_key -iv $encrypted_8ac6028fa38c_iv -in travis_labeler.enc -out deploy_key -d
  - bin/apply

before_deploy:
  - go get -u github.com/aktau/github-release

deploy:
  provider: script
  script: bin/dist
  on:
    tags: true
    branch: master

notifications:
  email:
    on_success: never
    on_failure: change
